### ISSUE TITLE
Problem deploying on github pages.

### ISSUE THREAD

**Issue by 0wwafa** [jeremyckahn/chitchatter#336]
I did everything as in the readme.

But I get this:
https://0wwafa.github.io/chitchatter

**Comment by jeremyckahn** [comment]
Hi @0wwafa, it appears that your `gh-pages` branch does not have an `index.html` file: https://github.com/0wwafa/chitchatter/tree/gh-pages

![Screenshot of gh-pages branch](https://github.com/user-attachments/assets/a635d3f9-83a0-4fc1-b9ae-9818e7f1d89b)

This would cause the infinite 404 redirect you're seeing. Looking at [the diff between your fork and mine](https://github.com/jeremyckahn/chitchatter/compare/develop...0wwafa:chitchatter:develop), I can see that [`peaceiris/actions-gh-pages`'s `publish_dir` parameter was changed to `./dist`](https://github.com/0wwafa/chitchatter/commit/9db0a1c8092eb5493725b84e55e0a353687a2a25). Your issue should be resolved by reverting the configuration back to:

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v4
  with:
    deploy_key: ${{ secrets.DEPLOY_KEY }}
    publish_dir: ./dist
    force_orphan: true
```
